/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package fornecedor;

import br.com.jmary.home.Home;
import gestor_new.Gestor_New;
import gestor_search.Menu_Pesquisa_Gestor;
import javax.swing.JTabbedPane;
import produto_por_fornecedor_new.Produto_Por_Fornecedor_New;
import produto_por_fornecedor_search.Menu_Pesquisa_Produto_Por_Fornecedor;

/**
 *
 * @author pc
 */
public class Fornecedor_Home extends javax.swing.JPanel {

    public Home                         Home;
    public Fornecedor_Home_Inicio       Inicio;
    public JTabbedPane                  tabHome;
    public Conjunto_Botoes_Fornecedor   Conjunto_Botoes;
        
    /**
     * Creates new form Fonema_E_Letra_Home
     * @param Home2
     */
    public Fornecedor_Home( Home Home2 ) {
        initComponents();
        
        Home                       = Home2;
        tabHome                    = new JTabbedPane();
        Conjunto_Botoes            = new Conjunto_Botoes_Fornecedor( this );
                                
        Inicio = new Fornecedor_Home_Inicio( this );
                
    }
    
    //////////////////////////////////////////////////////
    public Produto_Por_Fornecedor_New Produto_Por_Fornecedor_New;
    
    public Fornecedor_Home( Home Home2, Produto_Por_Fornecedor_New Produto_Por_Fornecedor_New2 ) {
        initComponents();
        
        Home                       = Home2;
        tabHome                    = new JTabbedPane();
        Conjunto_Botoes            = new Conjunto_Botoes_Fornecedor( this );
        
        Produto_Por_Fornecedor_New = Produto_Por_Fornecedor_New2;
                                
        Inicio = new Fornecedor_Home_Inicio( this, Produto_Por_Fornecedor_New2 );
                
    }
    //////////////////////////////////////////////////////
    
    //////////////////////////////////////////////////////
    public Menu_Pesquisa_Produto_Por_Fornecedor Menu_Pesquisa_Produto_Por_Fornecedor;
    
    public Fornecedor_Home( Home Home2, Menu_Pesquisa_Produto_Por_Fornecedor Menu_Pesquisa_Produto_Por_Fornecedor2 ) {
        initComponents();
        
        Home                       = Home2;
        tabHome                    = new JTabbedPane();
        Conjunto_Botoes            = new Conjunto_Botoes_Fornecedor( this );
        
        Menu_Pesquisa_Produto_Por_Fornecedor = Menu_Pesquisa_Produto_Por_Fornecedor2;
                                
        Inicio = new Fornecedor_Home_Inicio( this, Menu_Pesquisa_Produto_Por_Fornecedor2 );
                
    }
    //////////////////////////////////////////////////////
    
    //////////////////////////////////////////////////////
    public Menu_Pesquisa_Gestor Menu_Pesquisa_Gestor;
    
    public Fornecedor_Home( Home Home2, Menu_Pesquisa_Gestor Menu_Pesquisa_Gestor2 ) {
        initComponents();
        
        Home                       = Home2;
        tabHome                    = new JTabbedPane();
        Conjunto_Botoes            = new Conjunto_Botoes_Fornecedor( this );
        
        Menu_Pesquisa_Gestor = Menu_Pesquisa_Gestor2;
                                
        Inicio = new Fornecedor_Home_Inicio( this, Menu_Pesquisa_Gestor2 );
                
    }
    //////////////////////////////////////////////////////
    
    //////////////////////////////////////////////////////
    public Gestor_New Gestor_New;
    
    public Fornecedor_Home( Home Home2, Gestor_New Gestor_New2 ) {
        initComponents();
        
        Home                       = Home2;
        tabHome                    = new JTabbedPane();
        Conjunto_Botoes            = new Conjunto_Botoes_Fornecedor( this );
        
        Gestor_New                 = Gestor_New2;
                                
        Inicio = new Fornecedor_Home_Inicio( this, Gestor_New2 );
                
    }
    //////////////////////////////////////////////////////

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnHome = new javax.swing.JPanel();

        javax.swing.GroupLayout pnHomeLayout = new javax.swing.GroupLayout(pnHome);
        pnHome.setLayout(pnHomeLayout);
        pnHomeLayout.setHorizontalGroup(
            pnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        pnHomeLayout.setVerticalGroup(
            pnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 209, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel pnHome;
    // End of variables declaration//GEN-END:variables
}
