/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package usuario_new;

import java.awt.Color;
import usuario.Usuario_Home;

/**
 *
 * @author AnaMariana
 */
public class Usuario_New extends javax.swing.JPanel {

    Usuario_Home       Usuario_Home;
    public Usuario_New_Inicio Usuario_New_Inicio;
    /**
     * Creates new form Cliente
     * @param Usuario_Home2
     */
    public Usuario_New( Usuario_Home Usuario_Home2 ) {
        initComponents();
                        
        Usuario_Home = Usuario_Home2;
        Usuario_New_Inicio = new Usuario_New_Inicio(this);
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        chPermitirAcessar = new javax.swing.JCheckBox();
        jpPermitirAcesso = new javax.swing.JPanel();
        tfLogin = new javax.swing.JTextField();
        tfSenha = new javax.swing.JTextField();
        tfRepetirSenha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        chbDefinirPermissoes = new javax.swing.JCheckBox();
        jpPermissoes = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        chFornecedorAlterar = new javax.swing.JCheckBox();
        chFornecedorExcluir = new javax.swing.JCheckBox();
        chFornecedorCadastrar = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        chFornecedor = new javax.swing.JCheckBox();
        chFornecedorPesquisar = new javax.swing.JCheckBox();
        jPanel15 = new javax.swing.JPanel();
        chProdutoAlterar = new javax.swing.JCheckBox();
        chProdutoExcluir = new javax.swing.JCheckBox();
        chProdutoCadastrar = new javax.swing.JCheckBox();
        jPanel17 = new javax.swing.JPanel();
        chProduto = new javax.swing.JCheckBox();
        chProdutoPesquisar = new javax.swing.JCheckBox();
        jPanel23 = new javax.swing.JPanel();
        chProdutoXFornecedorAlterar = new javax.swing.JCheckBox();
        chProdutoXFornecedorExcluir = new javax.swing.JCheckBox();
        chProdutoXFornecedorCadastrar = new javax.swing.JCheckBox();
        jPanel24 = new javax.swing.JPanel();
        chProdutoXFornecedor = new javax.swing.JCheckBox();
        chProdutoXFornecedorPesquisar = new javax.swing.JCheckBox();
        jPanel25 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        chUsuarioAlterar = new javax.swing.JCheckBox();
        chUsuarioExcluir = new javax.swing.JCheckBox();
        chUsuarioCadastrar = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        chUsuario = new javax.swing.JCheckBox();
        chUsuarioPesquisar = new javax.swing.JCheckBox();
        jPanel18 = new javax.swing.JPanel();
        chGestorAlterar = new javax.swing.JCheckBox();
        chGestorExcluir = new javax.swing.JCheckBox();
        chGestorCadastrar = new javax.swing.JCheckBox();
        jPanel19 = new javax.swing.JPanel();
        chGestor = new javax.swing.JCheckBox();
        chGestorPesquisar = new javax.swing.JCheckBox();
        jPanel27 = new javax.swing.JPanel();
        chGestorAlterarEspVenda = new javax.swing.JCheckBox();
        chGestorAlterarEspEstoque = new javax.swing.JCheckBox();
        chGestorAlterarEspCusto = new javax.swing.JCheckBox();
        jPanel28 = new javax.swing.JPanel();
        chGestorAlterarEsp = new javax.swing.JCheckBox();
        chGestorAlterarEspPedido = new javax.swing.JCheckBox();
        jpStatus1 = new javax.swing.JPanel();
        btSalvar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Dados do Usuário");

        chPermitirAcessar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chPermitirAcessar.setSelected(true);
        chPermitirAcessar.setText("Permitir que este usuário acesse o sistema");
        chPermitirAcessar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chPermitirAcessarMousePressed(evt);
            }
        });
        chPermitirAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chPermitirAcessarActionPerformed(evt);
            }
        });

        jpPermitirAcesso.setBackground(new java.awt.Color(221, 219, 242));

        tfLogin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfLoginMouseExited(evt);
            }
        });
        tfLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfLoginKeyReleased(evt);
            }
        });

        tfSenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfSenha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfSenhaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfSenhaMouseExited(evt);
            }
        });
        tfSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfSenhaKeyReleased(evt);
            }
        });

        tfRepetirSenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfRepetirSenha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfRepetirSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfRepetirSenhaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfRepetirSenhaMouseExited(evt);
            }
        });
        tfRepetirSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfRepetirSenhaKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Repita a senha");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Definir senha");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Login (nome de usuário)");

        javax.swing.GroupLayout jpPermitirAcessoLayout = new javax.swing.GroupLayout(jpPermitirAcesso);
        jpPermitirAcesso.setLayout(jpPermitirAcessoLayout);
        jpPermitirAcessoLayout.setHorizontalGroup(
            jpPermitirAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPermitirAcessoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpPermitirAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPermitirAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfSenha)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPermitirAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfRepetirSenha)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jpPermitirAcessoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfLogin, tfRepetirSenha, tfSenha});

        jpPermitirAcessoLayout.setVerticalGroup(
            jpPermitirAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPermitirAcessoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpPermitirAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPermitirAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jpPermitirAcessoLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(2, 2, 2)
                            .addComponent(tfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jpPermitirAcessoLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(2, 2, 2)
                            .addComponent(tfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpPermitirAcessoLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(2, 2, 2)
                        .addComponent(tfRepetirSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jpPermitirAcessoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfLogin, tfRepetirSenha, tfSenha});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chPermitirAcessar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jpPermitirAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chPermitirAcessar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPermitirAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        chbDefinirPermissoes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chbDefinirPermissoes.setText("Definir permissões de acesso do usuário");
        chbDefinirPermissoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chbDefinirPermissoesMousePressed(evt);
            }
        });

        chFornecedorAlterar.setBackground(new java.awt.Color(255, 255, 255));
        chFornecedorAlterar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chFornecedorAlterar.setText("Alterar");
        chFornecedorAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chFornecedorAlterarMousePressed(evt);
            }
        });

        chFornecedorExcluir.setBackground(new java.awt.Color(255, 255, 255));
        chFornecedorExcluir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chFornecedorExcluir.setText("Excluir");
        chFornecedorExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chFornecedorExcluirMousePressed(evt);
            }
        });

        chFornecedorCadastrar.setBackground(new java.awt.Color(255, 255, 255));
        chFornecedorCadastrar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chFornecedorCadastrar.setText("Cadastrar");
        chFornecedorCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chFornecedorCadastrarMousePressed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(253, 254, 247));

        chFornecedor.setBackground(new java.awt.Color(255, 255, 255));
        chFornecedor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chFornecedor.setText("Fornecedor");
        chFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chFornecedorMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chFornecedor)
        );

        chFornecedorPesquisar.setBackground(new java.awt.Color(255, 255, 255));
        chFornecedorPesquisar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chFornecedorPesquisar.setText("Pesquisar");
        chFornecedorPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chFornecedorPesquisarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chFornecedorExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(chFornecedorCadastrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                .addComponent(chFornecedorAlterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(chFornecedorPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chFornecedorCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chFornecedorAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chFornecedorExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chFornecedorPesquisar)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        chProdutoAlterar.setBackground(new java.awt.Color(255, 255, 255));
        chProdutoAlterar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chProdutoAlterar.setText("Alterar");
        chProdutoAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chProdutoAlterarMousePressed(evt);
            }
        });

        chProdutoExcluir.setBackground(new java.awt.Color(255, 255, 255));
        chProdutoExcluir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chProdutoExcluir.setText("Excluir");
        chProdutoExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chProdutoExcluirMousePressed(evt);
            }
        });

        chProdutoCadastrar.setBackground(new java.awt.Color(255, 255, 255));
        chProdutoCadastrar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chProdutoCadastrar.setText("Cadastrar");
        chProdutoCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chProdutoCadastrarMousePressed(evt);
            }
        });

        jPanel17.setBackground(new java.awt.Color(253, 254, 247));

        chProduto.setBackground(new java.awt.Color(255, 255, 255));
        chProduto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chProduto.setText("Produto ");
        chProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chProdutoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chProduto)
        );

        chProdutoPesquisar.setBackground(new java.awt.Color(255, 255, 255));
        chProdutoPesquisar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chProdutoPesquisar.setText("Pesquisar");
        chProdutoPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chProdutoPesquisarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chProdutoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(chProdutoCadastrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                .addComponent(chProdutoAlterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(chProdutoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chProdutoCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chProdutoAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chProdutoExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chProdutoPesquisar)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        chProdutoXFornecedorAlterar.setBackground(new java.awt.Color(255, 255, 255));
        chProdutoXFornecedorAlterar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chProdutoXFornecedorAlterar.setText("Alterar");
        chProdutoXFornecedorAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chProdutoXFornecedorAlterarMousePressed(evt);
            }
        });

        chProdutoXFornecedorExcluir.setBackground(new java.awt.Color(255, 255, 255));
        chProdutoXFornecedorExcluir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chProdutoXFornecedorExcluir.setText("Excluir");
        chProdutoXFornecedorExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chProdutoXFornecedorExcluirMousePressed(evt);
            }
        });

        chProdutoXFornecedorCadastrar.setBackground(new java.awt.Color(255, 255, 255));
        chProdutoXFornecedorCadastrar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chProdutoXFornecedorCadastrar.setText("Cadastrar");
        chProdutoXFornecedorCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chProdutoXFornecedorCadastrarMousePressed(evt);
            }
        });

        jPanel24.setBackground(new java.awt.Color(253, 254, 247));

        chProdutoXFornecedor.setBackground(new java.awt.Color(255, 255, 255));
        chProdutoXFornecedor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chProdutoXFornecedor.setText("Produto X Fornecedor");
        chProdutoXFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chProdutoXFornecedorMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chProdutoXFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chProdutoXFornecedor)
        );

        chProdutoXFornecedorPesquisar.setBackground(new java.awt.Color(255, 255, 255));
        chProdutoXFornecedorPesquisar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chProdutoXFornecedorPesquisar.setText("Pesquisar");
        chProdutoXFornecedorPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chProdutoXFornecedorPesquisarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chProdutoXFornecedorExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(chProdutoXFornecedorCadastrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                .addComponent(chProdutoXFornecedorAlterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(chProdutoXFornecedorPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chProdutoXFornecedorCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chProdutoXFornecedorAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chProdutoXFornecedorExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chProdutoXFornecedorPesquisar)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        chUsuarioAlterar.setBackground(new java.awt.Color(255, 255, 255));
        chUsuarioAlterar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chUsuarioAlterar.setText("Alterar");
        chUsuarioAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chUsuarioAlterarMousePressed(evt);
            }
        });

        chUsuarioExcluir.setBackground(new java.awt.Color(255, 255, 255));
        chUsuarioExcluir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chUsuarioExcluir.setText("Excluir");
        chUsuarioExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chUsuarioExcluirMousePressed(evt);
            }
        });

        chUsuarioCadastrar.setBackground(new java.awt.Color(255, 255, 255));
        chUsuarioCadastrar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chUsuarioCadastrar.setText("Cadastrar");
        chUsuarioCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chUsuarioCadastrarMousePressed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(253, 254, 247));

        chUsuario.setBackground(new java.awt.Color(255, 255, 255));
        chUsuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chUsuario.setText("Usuário");
        chUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chUsuarioMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chUsuario)
        );

        chUsuarioPesquisar.setBackground(new java.awt.Color(255, 255, 255));
        chUsuarioPesquisar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chUsuarioPesquisar.setText("Pesquisar");
        chUsuarioPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chUsuarioPesquisarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chUsuarioExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(chUsuarioCadastrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                .addComponent(chUsuarioAlterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(chUsuarioPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chUsuarioCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chUsuarioAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chUsuarioExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chUsuarioPesquisar)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        chGestorAlterar.setBackground(new java.awt.Color(255, 255, 255));
        chGestorAlterar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chGestorAlterar.setText("Alterar");
        chGestorAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chGestorAlterarMousePressed(evt);
            }
        });

        chGestorExcluir.setBackground(new java.awt.Color(255, 255, 255));
        chGestorExcluir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chGestorExcluir.setText("Excluir");
        chGestorExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chGestorExcluirMousePressed(evt);
            }
        });

        chGestorCadastrar.setBackground(new java.awt.Color(255, 255, 255));
        chGestorCadastrar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chGestorCadastrar.setText("Cadastrar");
        chGestorCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chGestorCadastrarMousePressed(evt);
            }
        });

        jPanel19.setBackground(new java.awt.Color(253, 254, 247));

        chGestor.setBackground(new java.awt.Color(255, 255, 255));
        chGestor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chGestor.setText("Gestor ");
        chGestor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chGestorMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chGestor, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chGestor)
        );

        chGestorPesquisar.setBackground(new java.awt.Color(255, 255, 255));
        chGestorPesquisar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chGestorPesquisar.setText("Pesquisar");
        chGestorPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chGestorPesquisarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chGestorExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(chGestorCadastrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                .addComponent(chGestorAlterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(chGestorPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chGestorCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chGestorAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chGestorExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chGestorPesquisar)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        chGestorAlterarEspVenda.setBackground(new java.awt.Color(255, 255, 255));
        chGestorAlterarEspVenda.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chGestorAlterarEspVenda.setText("Venda");
        chGestorAlterarEspVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chGestorAlterarEspVendaMousePressed(evt);
            }
        });

        chGestorAlterarEspEstoque.setBackground(new java.awt.Color(255, 255, 255));
        chGestorAlterarEspEstoque.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chGestorAlterarEspEstoque.setText("Estoque");
        chGestorAlterarEspEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chGestorAlterarEspEstoqueMousePressed(evt);
            }
        });

        chGestorAlterarEspCusto.setBackground(new java.awt.Color(255, 255, 255));
        chGestorAlterarEspCusto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chGestorAlterarEspCusto.setText("Custo");
        chGestorAlterarEspCusto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chGestorAlterarEspCustoMousePressed(evt);
            }
        });

        jPanel28.setBackground(new java.awt.Color(253, 254, 247));

        chGestorAlterarEsp.setBackground(new java.awt.Color(255, 255, 255));
        chGestorAlterarEsp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chGestorAlterarEsp.setText("* Gestor - Alterar");
        chGestorAlterarEsp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chGestorAlterarEspMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chGestorAlterarEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chGestorAlterarEsp)
        );

        chGestorAlterarEspPedido.setBackground(new java.awt.Color(255, 255, 255));
        chGestorAlterarEspPedido.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chGestorAlterarEspPedido.setText("Pedido");
        chGestorAlterarEspPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chGestorAlterarEspPedidoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel27Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chGestorAlterarEspEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(chGestorAlterarEspCusto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chGestorAlterarEspVenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                            .addComponent(chGestorAlterarEspPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel27Layout.createSequentialGroup()
                .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chGestorAlterarEspCusto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chGestorAlterarEspVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chGestorAlterarEspEstoque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chGestorAlterarEspPedido)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jpPermissoesLayout = new javax.swing.GroupLayout(jpPermissoes);
        jpPermissoes.setLayout(jpPermissoesLayout);
        jpPermissoesLayout.setHorizontalGroup(
            jpPermissoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPermissoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPermissoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpPermissoesLayout.setVerticalGroup(
            jpPermissoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPermissoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpStatus1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(201, 239, 237)));

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/salvar.gif"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setEnabled(false);
        btSalvar.setPreferredSize(new java.awt.Dimension(91, 27));
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/atualizar.png"))); // NOI18N
        btAtualizar.setText("Atualizar");
        btAtualizar.setEnabled(false);

        javax.swing.GroupLayout jpStatus1Layout = new javax.swing.GroupLayout(jpStatus1);
        jpStatus1.setLayout(jpStatus1Layout);
        jpStatus1Layout.setHorizontalGroup(
            jpStatus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpStatus1Layout.createSequentialGroup()
                .addContainerGap(221, Short.MAX_VALUE)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAtualizar)
                .addContainerGap())
        );
        jpStatus1Layout.setVerticalGroup(
            jpStatus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpStatus1Layout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addGroup(jpStatus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAtualizar)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(chbDefinirPermissoes, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpPermissoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpStatus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbDefinirPermissoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpPermissoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chPermitirAcessarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chPermitirAcessarMousePressed
        
    }//GEN-LAST:event_chPermitirAcessarMousePressed

    private void chPermitirAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chPermitirAcessarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chPermitirAcessarActionPerformed

    private void chFornecedorAlterarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chFornecedorAlterarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_chFornecedorAlterarMousePressed

    private void chFornecedorExcluirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chFornecedorExcluirMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_chFornecedorExcluirMousePressed

    private void chFornecedorCadastrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chFornecedorCadastrarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_chFornecedorCadastrarMousePressed

    private void chFornecedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chFornecedorMousePressed
        if( chFornecedor.isEnabled() ){
            chFornecedorCadastrar  .setSelected( !chFornecedor.isSelected() );
            chFornecedorAlterar    .setSelected( !chFornecedor.isSelected() );
            chFornecedorExcluir    .setSelected( !chFornecedor.isSelected() );
            chFornecedorPesquisar  .setSelected( !chFornecedor.isSelected() );
        }
    }//GEN-LAST:event_chFornecedorMousePressed

    private void chFornecedorPesquisarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chFornecedorPesquisarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_chFornecedorPesquisarMousePressed

    private void chProdutoAlterarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chProdutoAlterarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_chProdutoAlterarMousePressed

    private void chProdutoExcluirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chProdutoExcluirMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_chProdutoExcluirMousePressed

    private void chProdutoCadastrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chProdutoCadastrarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_chProdutoCadastrarMousePressed

    private void chProdutoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chProdutoMousePressed
        if( chProduto.isEnabled() ){
            chProdutoCadastrar  .setSelected( !chProduto.isSelected() );
            chProdutoAlterar    .setSelected( !chProduto.isSelected() );
            chProdutoExcluir    .setSelected( !chProduto.isSelected() );
            chProdutoPesquisar  .setSelected( !chProduto.isSelected() );
        }
    }//GEN-LAST:event_chProdutoMousePressed

    private void chProdutoPesquisarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chProdutoPesquisarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_chProdutoPesquisarMousePressed

    private void chProdutoXFornecedorAlterarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chProdutoXFornecedorAlterarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_chProdutoXFornecedorAlterarMousePressed

    private void chProdutoXFornecedorExcluirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chProdutoXFornecedorExcluirMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_chProdutoXFornecedorExcluirMousePressed

    private void chProdutoXFornecedorCadastrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chProdutoXFornecedorCadastrarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_chProdutoXFornecedorCadastrarMousePressed

    private void chProdutoXFornecedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chProdutoXFornecedorMousePressed
        if( chProdutoXFornecedor.isEnabled() ){
            chProdutoXFornecedorCadastrar  .setSelected( !chProdutoXFornecedor.isSelected() );
            chProdutoXFornecedorAlterar    .setSelected( !chProdutoXFornecedor.isSelected() );
            chProdutoXFornecedorExcluir    .setSelected( !chProdutoXFornecedor.isSelected() );
            chProdutoXFornecedorPesquisar  .setSelected( !chProdutoXFornecedor.isSelected() );
        }
    }//GEN-LAST:event_chProdutoXFornecedorMousePressed

    private void chProdutoXFornecedorPesquisarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chProdutoXFornecedorPesquisarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_chProdutoXFornecedorPesquisarMousePressed

    private void chUsuarioAlterarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chUsuarioAlterarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_chUsuarioAlterarMousePressed

    private void chUsuarioExcluirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chUsuarioExcluirMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_chUsuarioExcluirMousePressed

    private void chUsuarioCadastrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chUsuarioCadastrarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_chUsuarioCadastrarMousePressed

    private void chUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chUsuarioMousePressed
        if( chUsuario.isEnabled() ){
            chUsuarioCadastrar  .setSelected( !chUsuario.isSelected() );
            chUsuarioAlterar    .setSelected( !chUsuario.isSelected() );
            chUsuarioExcluir    .setSelected( !chUsuario.isSelected() );
            chUsuarioPesquisar  .setSelected( !chUsuario.isSelected() );
        }
    }//GEN-LAST:event_chUsuarioMousePressed

    private void chUsuarioPesquisarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chUsuarioPesquisarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_chUsuarioPesquisarMousePressed

    private void chGestorAlterarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chGestorAlterarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_chGestorAlterarMousePressed

    private void chGestorExcluirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chGestorExcluirMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_chGestorExcluirMousePressed

    private void chGestorCadastrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chGestorCadastrarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_chGestorCadastrarMousePressed

    private void chGestorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chGestorMousePressed
        if( chGestor.isEnabled() ){
            chGestorCadastrar  .setSelected( !chGestor.isSelected() );
            chGestorAlterar    .setSelected( !chGestor.isSelected() );
            chGestorExcluir    .setSelected( !chGestor.isSelected() );
            chGestorPesquisar  .setSelected( !chGestor.isSelected() );
        }
    }//GEN-LAST:event_chGestorMousePressed

    private void chGestorPesquisarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chGestorPesquisarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_chGestorPesquisarMousePressed

    private void chGestorAlterarEspVendaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chGestorAlterarEspVendaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_chGestorAlterarEspVendaMousePressed

    private void chGestorAlterarEspEstoqueMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chGestorAlterarEspEstoqueMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_chGestorAlterarEspEstoqueMousePressed

    private void chGestorAlterarEspCustoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chGestorAlterarEspCustoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_chGestorAlterarEspCustoMousePressed

    private void chGestorAlterarEspMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chGestorAlterarEspMousePressed
        if( chGestorAlterarEsp.isEnabled() ){
            chGestorAlterarEspCusto   .setSelected( !chGestorAlterarEsp.isSelected() );
            chGestorAlterarEspVenda   .setSelected( !chGestorAlterarEsp.isSelected() );
            chGestorAlterarEspEstoque .setSelected( !chGestorAlterarEsp.isSelected() );
            chGestorAlterarEspPedido  .setSelected( !chGestorAlterarEsp.isSelected() );
        }
    }//GEN-LAST:event_chGestorAlterarEspMousePressed

    private void chGestorAlterarEspPedidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chGestorAlterarEspPedidoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_chGestorAlterarEspPedidoMousePressed

    private void chbDefinirPermissoesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chbDefinirPermissoesMousePressed
        configurarCbPermitirAcesso();
    }//GEN-LAST:event_chbDefinirPermissoesMousePressed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
         Usuario_New_Inicio.salvar( new usuario.Usuario() );
    }//GEN-LAST:event_btSalvarActionPerformed

    private void tfLoginKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfLoginKeyReleased
        evtBotaoSalvar();
    }//GEN-LAST:event_tfLoginKeyReleased

    private void tfSenhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSenhaKeyReleased
        evtBotaoSalvar();
    }//GEN-LAST:event_tfSenhaKeyReleased

    private void tfRepetirSenhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfRepetirSenhaKeyReleased
        evtBotaoSalvar();
    }//GEN-LAST:event_tfRepetirSenhaKeyReleased

    private void tfLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfLoginMouseEntered
        try{
            tfLogin.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
            tfLogin.setForeground(new java.awt.Color(0, 0, 204));
        
            tfLogin.setBackground(Color.YELLOW);
            tfLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));  
        }catch(Exception e ){}
    }//GEN-LAST:event_tfLoginMouseEntered

    private void tfLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfLoginMouseExited
        try{
            tfLogin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            tfLogin.setForeground(new java.awt.Color(0, 0, 0));
        
            tfLogin.setBackground(Color.WHITE);        
            tfLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        }catch(Exception e ){}        
    }//GEN-LAST:event_tfLoginMouseExited

    private void tfSenhaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfSenhaMouseEntered
        try{
            tfSenha.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
            tfSenha.setForeground(new java.awt.Color(0, 0, 204));
        
            tfSenha.setBackground(Color.YELLOW);
            tfSenha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));  
        }catch(Exception e ){}
    }//GEN-LAST:event_tfSenhaMouseEntered

    private void tfRepetirSenhaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfRepetirSenhaMouseEntered
        try{
            tfRepetirSenha.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
            tfRepetirSenha.setForeground(new java.awt.Color(0, 0, 204));
        
            tfRepetirSenha.setBackground(Color.YELLOW);
            tfRepetirSenha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));  
        }catch(Exception e ){}
    }//GEN-LAST:event_tfRepetirSenhaMouseEntered

    private void tfSenhaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfSenhaMouseExited
        try{
            tfSenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            tfSenha.setForeground(new java.awt.Color(0, 0, 0));
        
            tfSenha.setBackground(Color.WHITE);        
            tfSenha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        }catch(Exception e ){} 
    }//GEN-LAST:event_tfSenhaMouseExited

    private void tfRepetirSenhaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfRepetirSenhaMouseExited
        try{
            tfRepetirSenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            tfRepetirSenha.setForeground(new java.awt.Color(0, 0, 0));
        
            tfRepetirSenha.setBackground(Color.WHITE);        
            tfRepetirSenha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        }catch(Exception e ){} 
    }//GEN-LAST:event_tfRepetirSenhaMouseExited
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btAtualizar;
    public javax.swing.JButton btSalvar;
    public javax.swing.JCheckBox chFornecedor;
    public javax.swing.JCheckBox chFornecedorAlterar;
    public javax.swing.JCheckBox chFornecedorCadastrar;
    public javax.swing.JCheckBox chFornecedorExcluir;
    public javax.swing.JCheckBox chFornecedorPesquisar;
    public javax.swing.JCheckBox chGestor;
    public javax.swing.JCheckBox chGestorAlterar;
    public javax.swing.JCheckBox chGestorAlterarEsp;
    public javax.swing.JCheckBox chGestorAlterarEspCusto;
    public javax.swing.JCheckBox chGestorAlterarEspEstoque;
    public javax.swing.JCheckBox chGestorAlterarEspPedido;
    public javax.swing.JCheckBox chGestorAlterarEspVenda;
    public javax.swing.JCheckBox chGestorCadastrar;
    public javax.swing.JCheckBox chGestorExcluir;
    public javax.swing.JCheckBox chGestorPesquisar;
    public javax.swing.JCheckBox chPermitirAcessar;
    public javax.swing.JCheckBox chProduto;
    public javax.swing.JCheckBox chProdutoAlterar;
    public javax.swing.JCheckBox chProdutoCadastrar;
    public javax.swing.JCheckBox chProdutoExcluir;
    public javax.swing.JCheckBox chProdutoPesquisar;
    public javax.swing.JCheckBox chProdutoXFornecedor;
    public javax.swing.JCheckBox chProdutoXFornecedorAlterar;
    public javax.swing.JCheckBox chProdutoXFornecedorCadastrar;
    public javax.swing.JCheckBox chProdutoXFornecedorExcluir;
    public javax.swing.JCheckBox chProdutoXFornecedorPesquisar;
    public javax.swing.JCheckBox chUsuario;
    public javax.swing.JCheckBox chUsuarioAlterar;
    public javax.swing.JCheckBox chUsuarioCadastrar;
    public javax.swing.JCheckBox chUsuarioExcluir;
    public javax.swing.JCheckBox chUsuarioPesquisar;
    public javax.swing.JCheckBox chbDefinirPermissoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jpPermissoes;
    private javax.swing.JPanel jpPermitirAcesso;
    private javax.swing.JPanel jpStatus1;
    public javax.swing.JTextField tfLogin;
    public javax.swing.JTextField tfRepetirSenha;
    public javax.swing.JTextField tfSenha;
    // End of variables declaration//GEN-END:variables
    
    boolean permitirAcesso = true;
    public void configurarCbPermitirAcesso(){
        if( permitirAcesso == true ) {
            permitirAcesso = false;
            jpPermissoes.setVisible( false );
        } else if( permitirAcesso == false ) {
            permitirAcesso = true;
            jpPermissoes.setVisible( true );
        }
        
    }
    
    private void evtBotaoSalvar(){
        
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 ); 
            
            if( !tfLogin.getText().trim().equals( "" )  ){
                
                if( !tfSenha.getText().trim().equals( "" ) ){
                    
                    if( !tfRepetirSenha.getText().trim().equals( "" ) ){
                        btSalvar.setEnabled( true );
                    }
                    else{ btSalvar.setEnabled( false ); }
                } 
                else{ btSalvar.setEnabled( false ); }
            }        
            else{ btSalvar.setEnabled( false ); }
                                    
        } catch( Exception e ){ /*JOptionPaneMod JOptionPaneMod = new JOptionPaneMod( 2, "pesquisar(), \n"
                + e.getMessage() + "\n", "Menu_Pesquisa" );*/ } } }.start(); 
        
    }
            
}
