/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package produto_por_fornecedor_new;

import fornecedor.Fornecedor;
import fornecedor.Fornecedor_Home;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;
import produto.Produto;
import produto.Produto_Home;
import produto_por_fornecedor.Produto_Por_Fornecedor_Home;
import utilidades.JOPM;

/**
 *
 * @author pc
 */
public class Produto_Por_Fornecedor_New extends javax.swing.JPanel {
    
    public Produto_Por_Fornecedor_Home              Produto_Por_Fornecedor_Home;
    public Produto_Por_Fornecedor_New_Inicio Inicio;
    
    public Fornecedor Fornecedor = new Fornecedor();
    public Produto Produto = new Produto();

    /**
     * Creates new form Fornecedor_New
     * @param Produto_Por_Fornecedor_Home2
     */
    public Produto_Por_Fornecedor_New(Produto_Por_Fornecedor_Home Produto_Por_Fornecedor_Home2) {
        initComponents();
        
        Produto_Por_Fornecedor_Home  = Produto_Por_Fornecedor_Home2;
        Inicio                       = new Produto_Por_Fornecedor_New_Inicio( this );
        
    }
    
    ///////////////////////////////////////////////////////////////////////////
    public produto_por_fornecedor.Produtoporfornecedor Produtoporfornecedor;
    public Produto_Por_Fornecedor_New(Produto_Por_Fornecedor_Home Produto_Por_Fornecedor_Home2, produto_por_fornecedor.Produtoporfornecedor Produtoporfornecedor2 ) {
        initComponents();
        
        Produto_Por_Fornecedor_Home  = Produto_Por_Fornecedor_Home2;
        
        Produtoporfornecedor = Produtoporfornecedor2;
        
        Inicio = new Produto_Por_Fornecedor_New_Inicio( this, Produtoporfornecedor2 );
        
    }
    ///////////////////////////////////////////////////////////////////////////

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jpStatus1 = new javax.swing.JPanel();
        btSalvar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btCancelar1 = new javax.swing.JButton();
        tfFornecedor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lbFornecedor = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btCancelar2 = new javax.swing.JButton();
        tfProduto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lbFornecedor1 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Dados do Produto e do Fornecedor");

        jpStatus1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(201, 239, 237)));

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/salvar.gif"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSalvar.setPreferredSize(new java.awt.Dimension(91, 27));
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/atualizar.png"))); // NOI18N
        btAtualizar.setText("Atualizar");
        btAtualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAtualizar.setEnabled(false);
        btAtualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btAtualizarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jpStatus1Layout = new javax.swing.GroupLayout(jpStatus1);
        jpStatus1.setLayout(jpStatus1Layout);
        jpStatus1Layout.setHorizontalGroup(
            jpStatus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpStatus1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAtualizar)
                .addContainerGap())
        );
        jpStatus1Layout.setVerticalGroup(
            jpStatus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpStatus1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jpStatus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAtualizar)))
        );

        btCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/selecionar.png"))); // NOI18N
        btCancelar1.setText("Selecionar");
        btCancelar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCancelar1.setPreferredSize(new java.awt.Dimension(96, 25));
        btCancelar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btCancelar1MousePressed(evt);
            }
        });
        btCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelar1ActionPerformed(evt);
            }
        });

        tfFornecedor.setEditable(false);
        tfFornecedor.setBackground(new java.awt.Color(255, 255, 255));
        tfFornecedor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfFornecedor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tfFornecedor.setPreferredSize(new java.awt.Dimension(195, 23));
        tfFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfFornecedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfFornecedorMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfFornecedorMousePressed(evt);
            }
        });
        tfFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFornecedorActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Fornecedor");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });

        lbFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/clienteos.gif"))); // NOI18N
        lbFornecedor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        lbFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbFornecedorMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbFornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btCancelar1, tfFornecedor});

        btCancelar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/selecionar.png"))); // NOI18N
        btCancelar2.setText("Selecionar");
        btCancelar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCancelar2.setPreferredSize(new java.awt.Dimension(96, 25));
        btCancelar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btCancelar2MousePressed(evt);
            }
        });
        btCancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelar2ActionPerformed(evt);
            }
        });

        tfProduto.setEditable(false);
        tfProduto.setBackground(new java.awt.Color(255, 255, 255));
        tfProduto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfProduto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tfProduto.setPreferredSize(new java.awt.Dimension(195, 23));
        tfProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfProdutoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfProdutoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfProdutoMousePressed(evt);
            }
        });
        tfProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfProdutoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Produto");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });

        lbFornecedor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/carrinho.png"))); // NOI18N
        lbFornecedor1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        lbFornecedor1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbFornecedor1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbFornecedor1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbFornecedor1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tfProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCancelar2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbFornecedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancelar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jpStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpStatus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        Inicio.salvar( new produto_por_fornecedor.Produtoporfornecedor(), false );
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btAtualizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAtualizarMousePressed
        if( btAtualizar.isEnabled() == true ){
            
            //Inicio.setarCategorias( new categoria_do_produto.Categoriadoproduto() );
        }
    }//GEN-LAST:event_btAtualizarMousePressed

    private void tfFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFornecedorActionPerformed

    private void lbFornecedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbFornecedorMousePressed
        selecionarFornecedor();
    }//GEN-LAST:event_lbFornecedorMousePressed

    private void btCancelar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCancelar1MousePressed
        selecionarFornecedor();
    }//GEN-LAST:event_btCancelar1MousePressed

    private void btCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCancelar1ActionPerformed

    private void btCancelar2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCancelar2MousePressed
        selecionarProduto();
    }//GEN-LAST:event_btCancelar2MousePressed

    private void btCancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCancelar2ActionPerformed

    private void tfProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfProdutoActionPerformed

    private void lbFornecedor1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbFornecedor1MousePressed
        selecionarProduto();
    }//GEN-LAST:event_lbFornecedor1MousePressed

    private void tfFornecedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfFornecedorMouseEntered
        mouseEntra( tfFornecedor );
    }//GEN-LAST:event_tfFornecedorMouseEntered

    private void tfFornecedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfFornecedorMouseExited
        mouseSai( tfFornecedor );
    }//GEN-LAST:event_tfFornecedorMouseExited

    private void tfProdutoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfProdutoMouseEntered
        mouseEntra( tfProduto );
    }//GEN-LAST:event_tfProdutoMouseEntered

    private void tfProdutoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfProdutoMouseExited
        mouseSai( tfProduto );
    }//GEN-LAST:event_tfProdutoMouseExited

    private void tfFornecedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfFornecedorMousePressed
        selecionarFornecedor();
    }//GEN-LAST:event_tfFornecedorMousePressed

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        selecionarFornecedor();
    }//GEN-LAST:event_jLabel5MousePressed

    private void tfProdutoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfProdutoMousePressed
        selecionarProduto();
    }//GEN-LAST:event_tfProdutoMousePressed

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        selecionarProduto();
    }//GEN-LAST:event_jLabel6MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btAtualizar;
    public javax.swing.JButton btCancelar1;
    public javax.swing.JButton btCancelar2;
    public javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jpStatus1;
    public javax.swing.JLabel lbFornecedor;
    public javax.swing.JLabel lbFornecedor1;
    public javax.swing.JTextField tfFornecedor;
    public javax.swing.JTextField tfProduto;
    // End of variables declaration//GEN-END:variables

    private void mouseEntra(javax.swing.JComponent c) {                                                  
        try{
            c.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
            c.setForeground(new java.awt.Color(0, 0, 204));

            c.setBackground(Color.YELLOW);
            c.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));
        }catch(Exception e ){}
    }
    
    private void mouseSai(javax.swing.JComponent c) {                                                  
        try{
            c.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            c.setForeground(new java.awt.Color(0, 0, 0));

            c.setBackground(Color.WHITE);
            c.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        }catch(Exception e ){}
    }
    
    Produto_Por_Fornecedor_New Produto_Por_Fornecedor_New_Selecionar;
    private void selecionarFornecedor() {
        
        Produto_Por_Fornecedor_New_Selecionar = this;
        
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 ); 
            
            Fornecedor_Home Fornecedor_Home = new Fornecedor_Home( Produto_Por_Fornecedor_Home.Home, Produto_Por_Fornecedor_New_Selecionar );
            JPanel jp = new JPanel();
            jp.setLayout( new BorderLayout() );
            jp.add      ( Fornecedor_Home, BorderLayout.CENTER  );
            
            Produto_Por_Fornecedor_Home.Home.ControleTabs.AddTabSemControleNovo( Produto_Por_Fornecedor_Home.tabHome, "Selecionar Fornecedor", "/utilidades_imagens/icon.png", jp ); 
            
        } catch( Exception e ){ JOPM JOptionPaneMod = new JOPM( 2, "addAbaPesquisa(), \n"
                + e.getMessage() + "\n", this.getClass().getSimpleName() ); } } }.start();    
    }
    
    private void selecionarProduto() {                                                  
        Produto_Por_Fornecedor_New_Selecionar = this;
        
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 ); 

            Produto_Home Produto_Home = new Produto_Home( Produto_Por_Fornecedor_Home.Home, Produto_Por_Fornecedor_New_Selecionar );
            JPanel jp = new JPanel();
            jp.setLayout( new BorderLayout() );
            jp.add      ( Produto_Home, BorderLayout.CENTER  );
            
            Produto_Por_Fornecedor_Home.Home.ControleTabs.AddTabSemControleNovo( Produto_Por_Fornecedor_Home.tabHome, "Selecionar Produto", "/utilidades_imagens/icon.png", jp ); 
            
        } catch( Exception e ){ JOPM JOptionPaneMod = new JOPM( 2, "selecionarProduto(), \n"
                + e.getMessage() + "\n", this.getClass().getSimpleName() ); } } }.start(); 
    }
    
    public void setarNoJPanelFornecedorSelecionado( fornecedor.Fornecedor Fornecedor2 ) {                                                  
        try{

            Fornecedor = Fornecedor2;
            
            tfFornecedor.setText( Fornecedor.getNomeourazaosocial() );
            
        } catch( Exception e ){ JOPM JOptionPaneMod = new JOPM( 2, "setarNoJPanelFornecedorSelecionado(), \n"
                + e.getMessage() + "\n", this.getClass().getSimpleName() ); }
    }
    
    public void setarNoJPanelProdutoSelecionado( produto.Produto Produto2 ) {                                               
        try{

            try{

            Produto = Produto2;
            
            tfProduto.setText( Produto.getDescricaoproduto() );
            
        } catch( Exception e ){ JOPM JOptionPaneMod = new JOPM( 2, "setarNoJPanelProdutoSelecionado(), \n"
                + e.getMessage() + "\n", this.getClass().getSimpleName() ); }
            
        } catch( Exception e ){ JOPM JOptionPaneMod = new JOPM( 2, "setarNoJPanelProdutoSelecionado(), \n"
                + e.getMessage() + "\n", this.getClass().getSimpleName() ); }
    }
    
}