/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vizualizar_impressao;

import br.com.jmary.home.Home;
import javax.swing.JTabbedPane;

/**
 *
 * @author pc
 */
public class Imprimir_Home extends javax.swing.JPanel {
    
    public int                          IDGESTORRECEBIDA   = -1;

    public Home                  Home;
    public JTabbedPane           tabHome;
    public JTabbedPane           tabQueSeEncontra;
    
    public Imprimir_Home_Inicio  Inicio;
            
    /**
     * Creates new form Fonema_E_Letra_Home
     * @param IDGESTORRECEBIDA2
     * @param Home2
     * @param tab2
     */
    public Imprimir_Home( int IDGESTORRECEBIDA2, Home Home2, JTabbedPane tab2 ) {
        initComponents();
        
        IDGESTORRECEBIDA = IDGESTORRECEBIDA2;
        tabQueSeEncontra = tab2;
        
        Home                       = Home2;
        tabHome                    = new JTabbedPane();
                                        
        Inicio = new Imprimir_Home_Inicio( this );
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnHome = new javax.swing.JPanel();
        jpImprimirSup = new javax.swing.JPanel();
        jpImprimirCenter = new javax.swing.JScrollPane();

        javax.swing.GroupLayout jpImprimirSupLayout = new javax.swing.GroupLayout(jpImprimirSup);
        jpImprimirSup.setLayout(jpImprimirSupLayout);
        jpImprimirSupLayout.setHorizontalGroup(
            jpImprimirSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        jpImprimirSupLayout.setVerticalGroup(
            jpImprimirSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        jpImprimirCenter.setBorder(null);

        javax.swing.GroupLayout pnHomeLayout = new javax.swing.GroupLayout(pnHome);
        pnHome.setLayout(pnHomeLayout);
        pnHomeLayout.setHorizontalGroup(
            pnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpImprimirSup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpImprimirCenter)
        );
        pnHomeLayout.setVerticalGroup(
            pnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHomeLayout.createSequentialGroup()
                .addComponent(jpImprimirSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpImprimirCenter, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane jpImprimirCenter;
    public javax.swing.JPanel jpImprimirSup;
    public javax.swing.JPanel pnHome;
    // End of variables declaration//GEN-END:variables
    
}
