/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package fornecedor_new;

import fornecedor.Fornecedor_Home;
import java.awt.Color;
import javax.swing.JFormattedTextField;
import javax.swing.text.MaskFormatter;
import utilidades.JOPM;

/**
 *
 * @author pc
 */
public class Fornecedor_New extends javax.swing.JPanel {
    
    Fornecedor_Home              Fornecedor_Home;
    public Fornecedor_New_Inicio Inicio;

    /**
     * Creates new form Fornecedor_New
     */
    public Fornecedor_New(Fornecedor_Home Fornecedor_Home2) {
        initComponents();
        
        Fornecedor_Home       = Fornecedor_Home2;
        Inicio = new Fornecedor_New_Inicio( this );
        
    }
    
    ///////////////////////////////////////////////////////////////////////////
    public fornecedor.Fornecedor Fornecedor;
    public Fornecedor_New( Fornecedor_Home Fornecedor_Home2, fornecedor.Fornecedor Fornecedor2 ) {
        initComponents();
        
        Fornecedor_Home  = Fornecedor_Home2;
        
        Fornecedor = Fornecedor2;
        
        Inicio = new Fornecedor_New_Inicio( this, Fornecedor2 );
        
    }
    ///////////////////////////////////////////////////////////////////////////

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jpStatus1 = new javax.swing.JPanel();
        btSalvar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        jpPermitirAcesso = new javax.swing.JPanel();
        tfNomeouRazaoSocial = new javax.swing.JTextField();
        tfNomeVendedor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfTelefoneVendedor = new javax.swing.JFormattedTextField();
        jpPermitirAcesso1 = new javax.swing.JPanel();
        tfNomeFantasia = new javax.swing.JTextField();
        tfNomeSupervisor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfTelefoneSupervisor = new javax.swing.JFormattedTextField();
        jpPermitirAcesso2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        tfPrazoDePagamento = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfPrazoDeEntrega = new javax.swing.JTextField();
        tfCPFOuCNPJ = new javax.swing.JFormattedTextField();
        jpPermitirAcesso3 = new javax.swing.JPanel();
        rbPessoaFisica = new javax.swing.JRadioButton();
        rbPessoaJuridica = new javax.swing.JRadioButton();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Dados do Fornecedor");

        jpStatus1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(201, 239, 237)));

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/salvar.gif"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setPreferredSize(new java.awt.Dimension(91, 27));
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/atualizar.png"))); // NOI18N
        btAtualizar.setText("Atualizar");
        btAtualizar.setEnabled(false);

        javax.swing.GroupLayout jpStatus1Layout = new javax.swing.GroupLayout(jpStatus1);
        jpStatus1.setLayout(jpStatus1Layout);
        jpStatus1Layout.setHorizontalGroup(
            jpStatus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpStatus1Layout.createSequentialGroup()
                .addContainerGap(221, Short.MAX_VALUE)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAtualizar)
                .addContainerGap())
        );
        jpStatus1Layout.setVerticalGroup(
            jpStatus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpStatus1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jpStatus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAtualizar)))
        );

        tfNomeouRazaoSocial.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfNomeouRazaoSocial.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfNomeouRazaoSocial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfNomeouRazaoSocialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfNomeouRazaoSocialMouseExited(evt);
            }
        });
        tfNomeouRazaoSocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNomeouRazaoSocialKeyReleased(evt);
            }
        });

        tfNomeVendedor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfNomeVendedor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfNomeVendedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfNomeVendedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfNomeVendedorMouseExited(evt);
            }
        });
        tfNomeVendedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNomeVendedorKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Telefone Vendedor");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Nome Vendedor");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Nome ou Razão Social");

        tfTelefoneVendedor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        try {
            tfTelefoneVendedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfTelefoneVendedor.setPreferredSize(new java.awt.Dimension(185, 23));
        tfTelefoneVendedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfTelefoneVendedorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfTelefoneVendedorFocusLost(evt);
            }
        });
        tfTelefoneVendedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfTelefoneVendedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfTelefoneVendedorMouseExited(evt);
            }
        });
        tfTelefoneVendedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfTelefoneVendedorKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jpPermitirAcessoLayout = new javax.swing.GroupLayout(jpPermitirAcesso);
        jpPermitirAcesso.setLayout(jpPermitirAcessoLayout);
        jpPermitirAcessoLayout.setHorizontalGroup(
            jpPermitirAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPermitirAcessoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpPermitirAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfNomeouRazaoSocial, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPermitirAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfNomeVendedor)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPermitirAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfTelefoneVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );

        jpPermitirAcessoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfNomeVendedor, tfNomeouRazaoSocial, tfTelefoneVendedor});

        jpPermitirAcessoLayout.setVerticalGroup(
            jpPermitirAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPermitirAcessoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpPermitirAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPermitirAcessoLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(2, 2, 2)
                        .addComponent(tfNomeouRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPermitirAcessoLayout.createSequentialGroup()
                        .addGroup(jpPermitirAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(2, 2, 2)
                        .addGroup(jpPermitirAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNomeVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTelefoneVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jpPermitirAcessoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfNomeVendedor, tfNomeouRazaoSocial, tfTelefoneVendedor});

        tfNomeFantasia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfNomeFantasia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfNomeFantasia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfNomeFantasiaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfNomeFantasiaMouseExited(evt);
            }
        });
        tfNomeFantasia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNomeFantasiaKeyReleased(evt);
            }
        });

        tfNomeSupervisor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfNomeSupervisor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfNomeSupervisor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfNomeSupervisorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfNomeSupervisorMouseExited(evt);
            }
        });
        tfNomeSupervisor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNomeSupervisorKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Telefone Supervisor");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Nome Supervisor");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Nome Fantasia");

        tfTelefoneSupervisor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        try {
            tfTelefoneSupervisor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfTelefoneSupervisor.setPreferredSize(new java.awt.Dimension(185, 23));
        tfTelefoneSupervisor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfTelefoneSupervisorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfTelefoneSupervisorFocusLost(evt);
            }
        });
        tfTelefoneSupervisor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfTelefoneSupervisorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfTelefoneSupervisorMouseExited(evt);
            }
        });
        tfTelefoneSupervisor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfTelefoneSupervisorKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jpPermitirAcesso1Layout = new javax.swing.GroupLayout(jpPermitirAcesso1);
        jpPermitirAcesso1.setLayout(jpPermitirAcesso1Layout);
        jpPermitirAcesso1Layout.setHorizontalGroup(
            jpPermitirAcesso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPermitirAcesso1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpPermitirAcesso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfNomeFantasia, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPermitirAcesso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfNomeSupervisor, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPermitirAcesso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfTelefoneSupervisor, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );

        jpPermitirAcesso1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfNomeFantasia, tfNomeSupervisor, tfTelefoneSupervisor});

        jpPermitirAcesso1Layout.setVerticalGroup(
            jpPermitirAcesso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPermitirAcesso1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jpPermitirAcesso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPermitirAcesso1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(2, 2, 2)
                        .addComponent(tfNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPermitirAcesso1Layout.createSequentialGroup()
                        .addGroup(jpPermitirAcesso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(2, 2, 2)
                        .addGroup(jpPermitirAcesso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNomeSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTelefoneSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jpPermitirAcesso1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfNomeFantasia, tfNomeSupervisor, tfTelefoneSupervisor});

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Prazo de Pagamento");

        tfPrazoDePagamento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfPrazoDePagamento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfPrazoDePagamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfPrazoDePagamentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfPrazoDePagamentoMouseExited(evt);
            }
        });
        tfPrazoDePagamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPrazoDePagamentoKeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("CPF ou CNPJ");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Prazo de Entrega");

        tfPrazoDeEntrega.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfPrazoDeEntrega.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfPrazoDeEntrega.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfPrazoDeEntregaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfPrazoDeEntregaMouseExited(evt);
            }
        });
        tfPrazoDeEntrega.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPrazoDeEntregaKeyReleased(evt);
            }
        });

        tfCPFOuCNPJ.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        try {
            tfCPFOuCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfCPFOuCNPJ.setPreferredSize(new java.awt.Dimension(185, 23));
        tfCPFOuCNPJ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCPFOuCNPJFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCPFOuCNPJFocusLost(evt);
            }
        });
        tfCPFOuCNPJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfCPFOuCNPJMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfCPFOuCNPJMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfCPFOuCNPJMousePressed(evt);
            }
        });
        tfCPFOuCNPJ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCPFOuCNPJKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jpPermitirAcesso2Layout = new javax.swing.GroupLayout(jpPermitirAcesso2);
        jpPermitirAcesso2.setLayout(jpPermitirAcesso2Layout);
        jpPermitirAcesso2Layout.setHorizontalGroup(
            jpPermitirAcesso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPermitirAcesso2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPermitirAcesso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(tfCPFOuCNPJ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPermitirAcesso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPermitirAcesso2Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tfPrazoDePagamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPermitirAcesso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPrazoDeEntrega))
                .addContainerGap())
        );
        jpPermitirAcesso2Layout.setVerticalGroup(
            jpPermitirAcesso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPermitirAcesso2Layout.createSequentialGroup()
                .addGroup(jpPermitirAcesso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jpPermitirAcesso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jpPermitirAcesso2Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addGap(24, 24, 24))
                        .addGroup(jpPermitirAcesso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfPrazoDePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCPFOuCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpPermitirAcesso2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(2, 2, 2)
                        .addComponent(tfPrazoDeEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        rbPessoaFisica.setText("Pessoa Física");
        rbPessoaFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPessoaFisicaActionPerformed(evt);
            }
        });

        rbPessoaJuridica.setText("Pessoa Jurídica");
        rbPessoaJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPessoaJuridicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPermitirAcesso3Layout = new javax.swing.GroupLayout(jpPermitirAcesso3);
        jpPermitirAcesso3.setLayout(jpPermitirAcesso3Layout);
        jpPermitirAcesso3Layout.setHorizontalGroup(
            jpPermitirAcesso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPermitirAcesso3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbPessoaFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbPessoaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpPermitirAcesso3Layout.setVerticalGroup(
            jpPermitirAcesso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPermitirAcesso3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPermitirAcesso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbPessoaFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbPessoaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpPermitirAcesso1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpPermitirAcesso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpPermitirAcesso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpPermitirAcesso3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 31, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpStatus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPermitirAcesso3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPermitirAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPermitirAcesso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPermitirAcesso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        Inicio.salvar( new fornecedor.Fornecedor(), false );
    }//GEN-LAST:event_btSalvarActionPerformed

    private void tfNomeouRazaoSocialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNomeouRazaoSocialMouseEntered
        mouseEntra( tfNomeouRazaoSocial );
    }//GEN-LAST:event_tfNomeouRazaoSocialMouseEntered

    private void tfNomeouRazaoSocialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNomeouRazaoSocialMouseExited
        mouseSai( tfNomeouRazaoSocial );
    }//GEN-LAST:event_tfNomeouRazaoSocialMouseExited

    private void tfNomeouRazaoSocialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNomeouRazaoSocialKeyReleased

    }//GEN-LAST:event_tfNomeouRazaoSocialKeyReleased

    private void tfNomeVendedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNomeVendedorMouseEntered
        mouseEntra( tfNomeVendedor );
    }//GEN-LAST:event_tfNomeVendedorMouseEntered

    private void tfNomeVendedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNomeVendedorMouseExited
        mouseSai( tfNomeVendedor );
    }//GEN-LAST:event_tfNomeVendedorMouseExited

    private void tfNomeVendedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNomeVendedorKeyReleased

    }//GEN-LAST:event_tfNomeVendedorKeyReleased

    private void tfTelefoneVendedorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTelefoneVendedorFocusGained
        setarFocusGainedTelefone( tfTelefoneVendedor );
    }//GEN-LAST:event_tfTelefoneVendedorFocusGained

    private void tfTelefoneVendedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTelefoneVendedorFocusLost
        setarFocusLostTelefone( tfTelefoneVendedor );
    }//GEN-LAST:event_tfTelefoneVendedorFocusLost

    private void tfTelefoneVendedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTelefoneVendedorKeyReleased
     
    }//GEN-LAST:event_tfTelefoneVendedorKeyReleased

    private void tfTelefoneVendedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfTelefoneVendedorMouseEntered
        mouseEntra( tfTelefoneVendedor );
    }//GEN-LAST:event_tfTelefoneVendedorMouseEntered

    private void tfTelefoneVendedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfTelefoneVendedorMouseExited
        mouseSai( tfTelefoneVendedor );
    }//GEN-LAST:event_tfTelefoneVendedorMouseExited

    private void tfNomeFantasiaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNomeFantasiaMouseEntered
        mouseEntra( tfNomeFantasia );
    }//GEN-LAST:event_tfNomeFantasiaMouseEntered

    private void tfNomeFantasiaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNomeFantasiaMouseExited
        mouseSai( tfNomeFantasia );
    }//GEN-LAST:event_tfNomeFantasiaMouseExited

    private void tfNomeFantasiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNomeFantasiaKeyReleased
   
    }//GEN-LAST:event_tfNomeFantasiaKeyReleased

    private void tfNomeSupervisorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNomeSupervisorMouseEntered
        mouseEntra( tfNomeSupervisor );
    }//GEN-LAST:event_tfNomeSupervisorMouseEntered

    private void tfNomeSupervisorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNomeSupervisorMouseExited
        mouseSai( tfNomeSupervisor );
    }//GEN-LAST:event_tfNomeSupervisorMouseExited

    private void tfNomeSupervisorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNomeSupervisorKeyReleased

    }//GEN-LAST:event_tfNomeSupervisorKeyReleased

    private void tfTelefoneSupervisorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTelefoneSupervisorFocusGained
        setarFocusGainedTelefone( tfTelefoneSupervisor );
    }//GEN-LAST:event_tfTelefoneSupervisorFocusGained

    private void tfTelefoneSupervisorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTelefoneSupervisorFocusLost
        setarFocusLostTelefone( tfTelefoneSupervisor );
    }//GEN-LAST:event_tfTelefoneSupervisorFocusLost

    private void tfTelefoneSupervisorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfTelefoneSupervisorMouseEntered
        mouseEntra( tfTelefoneSupervisor );
    }//GEN-LAST:event_tfTelefoneSupervisorMouseEntered

    private void tfTelefoneSupervisorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfTelefoneSupervisorMouseExited
        mouseSai( tfTelefoneSupervisor );
    }//GEN-LAST:event_tfTelefoneSupervisorMouseExited

    private void tfTelefoneSupervisorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTelefoneSupervisorKeyReleased
  
    }//GEN-LAST:event_tfTelefoneSupervisorKeyReleased

    private void tfPrazoDePagamentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfPrazoDePagamentoMouseEntered
        mouseEntra( tfPrazoDePagamento );
    }//GEN-LAST:event_tfPrazoDePagamentoMouseEntered

    private void tfPrazoDePagamentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfPrazoDePagamentoMouseExited
        mouseSai( tfPrazoDePagamento );
    }//GEN-LAST:event_tfPrazoDePagamentoMouseExited

    private void tfPrazoDePagamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPrazoDePagamentoKeyReleased
 
    }//GEN-LAST:event_tfPrazoDePagamentoKeyReleased

    private void tfPrazoDeEntregaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfPrazoDeEntregaMouseEntered
        mouseEntra( tfPrazoDeEntrega );
    }//GEN-LAST:event_tfPrazoDeEntregaMouseEntered

    private void tfPrazoDeEntregaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfPrazoDeEntregaMouseExited
        mouseSai( tfPrazoDeEntrega );
    }//GEN-LAST:event_tfPrazoDeEntregaMouseExited

    private void tfPrazoDeEntregaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPrazoDeEntregaKeyReleased
 
    }//GEN-LAST:event_tfPrazoDeEntregaKeyReleased

    private void tfCPFOuCNPJMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfCPFOuCNPJMousePressed
        if( rbPessoaJuridica.isSelected() || rbPessoaFisica.isSelected() ){
        }
        else{

            JOPM JOptionPaneMod = new JOPM( 2, "O Campo Pessoa Física ou Jurídica não pode ser nulo"
                + "\nEscolha um dos ítens"
                + "\nExemplo:"
                + "\n    Pessoa Física"
                + "\n    Pessoa Jurídica"
                , "Pessoa Física ou Jurídica" );
            rbPessoaFisica.requestFocus();
        }
    }//GEN-LAST:event_tfCPFOuCNPJMousePressed

    private void tfCPFOuCNPJFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCPFOuCNPJFocusGained
        if( rbPessoaJuridica.isSelected() || rbPessoaFisica.isSelected() ){

            if( rbPessoaFisica.isSelected() ){

                setarFocusGainedCPF( tfCPFOuCNPJ );
            }
            else if( rbPessoaJuridica.isSelected() ){

                setarFocusGainedCNPJ( tfCPFOuCNPJ );
            }
        }
    }//GEN-LAST:event_tfCPFOuCNPJFocusGained

    private void tfCPFOuCNPJFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCPFOuCNPJFocusLost
        if( rbPessoaJuridica.isSelected() || rbPessoaFisica.isSelected() ){

            if( rbPessoaFisica.isSelected() ){

                setarFocusLostCPF( tfCPFOuCNPJ );
            }
            else if( rbPessoaJuridica.isSelected() ){

                setarFocusLostCNPJ( tfCPFOuCNPJ );
            }
        }
    }//GEN-LAST:event_tfCPFOuCNPJFocusLost

    private void rbPessoaFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPessoaFisicaActionPerformed
        tfCPFOuCNPJ.setValue("");
        rbPessoaJuridica.setSelected(false);
        rbPessoaFisicaMascara();
  
    }//GEN-LAST:event_rbPessoaFisicaActionPerformed

    private void rbPessoaJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPessoaJuridicaActionPerformed
        tfCPFOuCNPJ.setValue("");
        rbPessoaFisica.setSelected(false);
        rbPessoaJuridicaMascara();
   

    }//GEN-LAST:event_rbPessoaJuridicaActionPerformed

    private void tfCPFOuCNPJKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCPFOuCNPJKeyReleased
    
    }//GEN-LAST:event_tfCPFOuCNPJKeyReleased

    private void tfCPFOuCNPJMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfCPFOuCNPJMouseEntered
        mouseEntra( tfCPFOuCNPJ );
    }//GEN-LAST:event_tfCPFOuCNPJMouseEntered

    private void tfCPFOuCNPJMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfCPFOuCNPJMouseExited
        mouseSai( tfCPFOuCNPJ );
    }//GEN-LAST:event_tfCPFOuCNPJMouseExited

    private void rbPessoaFisicaMascara(){                                               
        try {
                
                MaskFormatter mascara = new MaskFormatter("###.###.###-##");
                mascara.setValidCharacters("0123456789");
                
                tfCPFOuCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory( mascara ) );                
            } catch ( Exception e ) {
                JOPM JOptionPaneMod = new JOPM( 2, "Erro ao setar Máscara, "
                        +"\n" + e.toString()
                                , "Erro ao setar Máscara" );
                        tfCPFOuCNPJ.requestFocus();
            } 
    }
    
    private void rbPessoaJuridicaMascara(){                                               
        try {
                
                MaskFormatter mascaraTelefone = new MaskFormatter("##.###.###/####-##");
                mascaraTelefone.setValidCharacters("0123456789");
                
                tfCPFOuCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory( mascaraTelefone ) );                
            } catch ( Exception e ) {
                JOPM JOptionPaneMod = new JOPM( 2, "Erro ao setar Máscara, "
                        +"\n" + e.toString()
                                , "Erro ao setar Máscara" );
                        tfCPFOuCNPJ.requestFocus();
            }
    }
    
    private void setarFocusGainedCNPJ( JFormattedTextField ftm ) {
        if( ftm.getText().trim().equals("") || ftm.getText().trim().equals(".   .   /    -") ){   
            
            try {
                
                MaskFormatter mascaraTelefone = new MaskFormatter("##.###.###/####-##");
                mascaraTelefone.setValidCharacters("0123456789");
                
                ftm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory( mascaraTelefone ) );                
            } catch ( Exception e ) {
                JOPM JOptionPaneMod = new JOPM( 2, "Erro ao setar Máscara, "
                        +"\n" + e.toString()
                                , "Erro ao setar Máscara" );
                        tfCPFOuCNPJ.requestFocus();
            }
            ftm.setText( "" );            
        }                
    }
    
    public void setarFocusLostCNPJ( JFormattedTextField ftm ) {
                
        if( !ftm.getText().trim().equals("") ){  
            
            if( ftm.getText().trim().length() < 18 ){ ftm.setValue( "" );
                
                try {                    
                    MaskFormatter mascara = new MaskFormatter(""); 
                    ftm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory( mascara ) );
                    ftm.setText( "" ); 
                } catch ( Exception e ) {
                    JOPM JOptionPaneMod = new JOPM( 2, "Erro ao setar Máscara, "
                        +"\n" + e.toString()
                                , "Erro ao setar Máscara" );
                        tfCPFOuCNPJ.requestFocus();
                }
            }
        }              
    }
    
    private void setarFocusGainedCPF( JFormattedTextField ftm ) {
        if( ftm.getText().trim().equals("") || ftm.getText().trim().equals(".   .   -") ){   
            
            try {
                
                MaskFormatter mascara = new MaskFormatter("###.###.###-##");
                mascara.setValidCharacters("0123456789");
                
                ftm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory( mascara ) );                
            } catch ( Exception e ) {
                JOPM JOptionPaneMod = new JOPM( 2, "Erro ao setar Máscara, "
                        +"\n" + e.toString()
                                , "Erro ao setar Máscara" );
                        tfCPFOuCNPJ.requestFocus();
            }
            ftm.setText( "" );            
        }                
    }
    
    public void setarFocusLostCPF( JFormattedTextField ftm ) {
                
        if( !ftm.getText().trim().equals("") ){  
            
            if( ftm.getText().trim().length() < 14 ){ ftm.setValue( "" );
                
                try {                    
                    MaskFormatter mascara = new MaskFormatter(""); 
                    ftm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory( mascara ) );
                    ftm.setText( "" ); 
                } catch ( Exception e ) {
                    JOPM JOptionPaneMod = new JOPM( 2, "Erro ao setar Máscara, "
                        +"\n" + e.toString()
                                , "Erro ao setar Máscara" );
                        tfCPFOuCNPJ.requestFocus();
                }
            }
        }              
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btAtualizar;
    public javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jpPermitirAcesso;
    private javax.swing.JPanel jpPermitirAcesso1;
    private javax.swing.JPanel jpPermitirAcesso2;
    private javax.swing.JPanel jpPermitirAcesso3;
    private javax.swing.JPanel jpStatus1;
    public javax.swing.JRadioButton rbPessoaFisica;
    public javax.swing.JRadioButton rbPessoaJuridica;
    public javax.swing.JFormattedTextField tfCPFOuCNPJ;
    public javax.swing.JTextField tfNomeFantasia;
    public javax.swing.JTextField tfNomeSupervisor;
    public javax.swing.JTextField tfNomeVendedor;
    public javax.swing.JTextField tfNomeouRazaoSocial;
    public javax.swing.JTextField tfPrazoDeEntrega;
    public javax.swing.JTextField tfPrazoDePagamento;
    public javax.swing.JFormattedTextField tfTelefoneSupervisor;
    public javax.swing.JFormattedTextField tfTelefoneVendedor;
    // End of variables declaration//GEN-END:variables

    private void mouseEntra(javax.swing.JComponent c) {                                                  
        try{
            c.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
            c.setForeground(new java.awt.Color(0, 0, 204));

            c.setBackground(Color.YELLOW);
            c.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));
        }catch(Exception e ){}
    }
    
    private void mouseSai(javax.swing.JComponent c) {                                                  
        try{
            c.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            c.setForeground(new java.awt.Color(0, 0, 0));

            c.setBackground(Color.WHITE);
            c.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        }catch(Exception e ){}
    }
    
    private void setarFocusGainedTelefone( JFormattedTextField ftm ) {
        if( ftm.getText().trim().equals("") || ftm.getText().trim().equals("+    (    )      -") ){   
            
            try {
                
                MaskFormatter mascaraTelefone = new MaskFormatter("+ ## ( ## ) #### - ####");
                mascaraTelefone.setValidCharacters("0123456789");
                
                ftm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory( mascaraTelefone ) );                
            } catch ( Exception e ) {
                JOPM JOptionPaneMod = new JOPM( 2, "Erro ao setar Máscara, "
                        +"\n" + e.toString()
                                , "Erro ao setar Máscara" );
                        ftm.requestFocus();
            }
            ftm.setText( "5585" );            
        }                
    } 
    
    public void setarFocusLostTelefone( JFormattedTextField ftm ) {
                
        if( !ftm.getText().trim().equals("") ){  
            
            if( ftm.getText().trim().length() < 23 ){ ftm.setValue( "" );
                
                try {                    
                    MaskFormatter mascaraTelefone = new MaskFormatter(""); 
                    ftm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory( mascaraTelefone ) );
                    ftm.setText( "" ); 
                } catch ( Exception e ) {
                    JOPM JOptionPaneMod = new JOPM( 2, "Erro ao setar Máscara, "
                        +"\n" + e.toString()
                                , "Erro ao setar Máscara" );
                        ftm.requestFocus();
                }
            }
        }              
    }
    
}
