/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package produto_por_fornecedor_search;

import fornecedor.Fornecedor_Home;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.List;
import javax.persistence.Query;
import javax.swing.JPanel;
import jpa.JPAUtil;
import produto_new.BookInfoCategoriaDoProduto;
import produto_por_fornecedor.Produto_Por_Fornecedor_Home;
import produto_por_fornecedor_new.Produto_Por_Fornecedor_New;
import gestor.Gestor_Home;
import jpa.DAOGenericoJPA;
import print.ControleThread_Print;
import utilidades.JOPM;

/**
 *
 * @author AnaMariana
 */
public class Menu_Pesquisa_Produto_Por_Fornecedor extends javax.swing.JPanel {

    public Produto_Por_Fornecedor_Home Produto_Por_Fornecedor_Home;
    public  int   IDSELECIONADA; 
    public Tabela_Pesquisa_BD_Produto_Por_Fornecedor Tabela_Pesquisa_BD_Produto_Por_Fornecedor;
    
    private Query q = null;
     
    /**
     * Creates new form Cliente
     */
    public Menu_Pesquisa_Produto_Por_Fornecedor( Produto_Por_Fornecedor_Home Produto_Por_Fornecedor_Home2 ) {
        initComponents();
                        
        Produto_Por_Fornecedor_Home = Produto_Por_Fornecedor_Home2;
        
        inicioCBS();
    }
    
    private void inicioCBS(){        
        cbTipoDePesquisa.setBackground( new Color( 255, 255, 255 ) );   
        cbCategoriaDoProduto.setBackground( new Color( 255, 255, 255 ) ); 
        
        setarCategorias( new categoria_do_produto.Categoriadoproduto() );
        
        lbCategoria.setVisible(false);
        cbCategoriaDoProduto.setVisible(false);
    }
    
    public void tabela(Tabela_Pesquisa_BD_Produto_Por_Fornecedor Tabela_Pesquisa_BD_Produto_Por_Fornecedor2){ 
                
        try {                
            Tabela_Pesquisa_BD_Produto_Por_Fornecedor = Tabela_Pesquisa_BD_Produto_Por_Fornecedor2;                                    
        } catch( Exception e ){ e.printStackTrace(); JOPM JOptionPaneMod = new JOPM( 2, "tabela, \n"
                + e.getMessage() + "\n", this.getClass().getSimpleName() ); }     
    }
                
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        cbTipoDePesquisa = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cbCategoriaDoProduto = new javax.swing.JComboBox();
        lbCategoria = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tfPesquisa1 = new javax.swing.JTextField();
        btSelecionar1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btSelecionar = new javax.swing.JButton();
        tfPesquisa = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btExcluir = new javax.swing.JButton();
        btVisualizar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        jpStatus1 = new javax.swing.JPanel();
        btPrint = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btGestor = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Dados do Produto Por Fornecedor");

        jPanel5.setBackground(new java.awt.Color(253, 254, 247));

        jPanel7.setBackground(new java.awt.Color(253, 254, 247));

        cbTipoDePesquisa.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cbTipoDePesquisa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CÓDIGO DO PRODUTO", "DESCRIÇÃO DO PRODUTO", "CATEGORIA DO PRODUTO" }));
        cbTipoDePesquisa.setSelectedIndex(1);
        cbTipoDePesquisa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        cbTipoDePesquisa.setPreferredSize(new java.awt.Dimension(212, 23));
        cbTipoDePesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoDePesquisaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Pesquisar por:");

        cbCategoriaDoProduto.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cbCategoriaDoProduto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        cbCategoriaDoProduto.setPreferredSize(new java.awt.Dimension(212, 23));
        cbCategoriaDoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoriaDoProdutoActionPerformed(evt);
            }
        });

        lbCategoria.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbCategoria.setText("Categoria");

        jPanel1.setBackground(new java.awt.Color(253, 254, 247));

        tfPesquisa1.setPreferredSize(new java.awt.Dimension(399, 24));
        tfPesquisa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfPesquisa1MousePressed(evt);
            }
        });
        tfPesquisa1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPesquisa1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tfPesquisa1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(tfPesquisa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        btSelecionar1.setText("Pesquisar");
        btSelecionar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSelecionar1.setPreferredSize(new java.awt.Dimension(96, 25));
        btSelecionar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btSelecionar1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSelecionar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbTipoDePesquisa, 0, 233, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbCategoriaDoProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lbCategoria)
                        .addGap(5, 5, 5)
                        .addComponent(cbCategoriaDoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(5, 5, 5)
                        .addComponent(cbTipoDePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSelecionar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(253, 254, 247));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Selecione um Fornecedor");

        btSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/selecionar.png"))); // NOI18N
        btSelecionar.setText("Selecionar");
        btSelecionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSelecionar.setPreferredSize(new java.awt.Dimension(96, 25));
        btSelecionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btSelecionarMousePressed(evt);
            }
        });

        tfPesquisa.setEditable(false);
        tfPesquisa.setBackground(new java.awt.Color(255, 255, 255));
        tfPesquisa.setPreferredSize(new java.awt.Dimension(399, 24));
        tfPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfPesquisaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(tfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/exluir.gif"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setEnabled(false);
        btExcluir.setPreferredSize(new java.awt.Dimension(97, 25));
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btVisualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/olho.png"))); // NOI18N
        btVisualizar.setText("Visualizar");
        btVisualizar.setEnabled(false);
        btVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVisualizarActionPerformed(evt);
            }
        });

        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/alterar.gif"))); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.setEnabled(false);
        btAlterar.setPreferredSize(new java.awt.Dimension(97, 27));
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btVisualizar)
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btAlterar, btExcluir, btVisualizar});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btAlterar, btVisualizar});

        jpStatus1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(201, 239, 237)));

        btPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/printv.png"))); // NOI18N
        btPrint.setText("Print");
        btPrint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPrint.setEnabled(false);
        btPrint.setPreferredSize(new java.awt.Dimension(91, 27));
        btPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrintActionPerformed(evt);
            }
        });

        btAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/atualizar.png"))); // NOI18N
        btAtualizar.setText("Atualizar");
        btAtualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAtualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btAtualizarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jpStatus1Layout = new javax.swing.GroupLayout(jpStatus1);
        jpStatus1.setLayout(jpStatus1Layout);
        jpStatus1Layout.setHorizontalGroup(
            jpStatus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpStatus1Layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(btAtualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpStatus1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btAtualizar, btPrint});

        jpStatus1Layout.setVerticalGroup(
            jpStatus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpStatus1Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addGroup(jpStatus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPrint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAtualizar)))
        );

        jpStatus1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btAtualizar, btPrint});

        jToolBar1.setRollover(true);
        jToolBar1.setPreferredSize(new java.awt.Dimension(91, 25));

        btGestor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fonema_e_letra_imagens/os.png"))); // NOI18N
        btGestor.setText("Gerar Gestor");
        btGestor.setEnabled(false);
        btGestor.setFocusable(false);
        btGestor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btGestor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btGestor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btGestorMousePressed(evt);
            }
        });
        jToolBar1.add(btGestor);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addComponent(jpStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jpStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jpStatus1});

    }// </editor-fold>//GEN-END:initComponents

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        excluir();
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 ); 
             alterarOuVisualizar( "Alterar" );    
        } catch( Exception e ){      } } }.start();       
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVisualizarActionPerformed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 ); 
             alterarOuVisualizar( "Visualizar" );  
        } catch( Exception e ){      } } }.start(); 
    }//GEN-LAST:event_btVisualizarActionPerformed

    private void tfPesquisaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfPesquisaMousePressed
        selecionarFornecedor();
    }//GEN-LAST:event_tfPesquisaMousePressed

    private void btPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrintActionPerformed
        /*new Thread() {   @Override public void run() { try { Thread.sleep( 1 ); 
        
            if( btPrint.isEnabled() ) {
            
                if( IDSELECIONADA > 0 ) {
                    
                    fornecedor.Fornecedor Fornecedor4 = getFornecedor();
                    
                    if( Fornecedor4.getId() > 0 ) {
                        
                    //
                        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );  
                        
                            ControleThread_Print t1 = new ControleThread_Print( getFornecedor().getId(), 2 );         
                            t1.setName("ControleThread_Print");           
                            t1.start();
                            
                        } catch( Exception e ){ JOPM JOPM = new JOPM( 2, "eventoBotaoImprimir(), \n" + e.getMessage() + "\n", this.getClass().getSimpleName() ); } } }.start(); 
                   
                    }
                    else{
                        JOPM JOptionPaneMod = new JOPM( 2, "Fornecedor Selecionado, \n"
                                + "Nenhum Fornecedor Selecionado\n" 
                                + "Para Gerar um Novo Gestor Selecione um Fornecedor" 
                                + "\n", "Fornecedor Selecionado" );
                    }
                    
                }
            }
        
        } catch( Exception e ){      } } }.start();   */  
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 ); 
            
            String tf = "";
            if( !tfPesquisa1.getText().trim().equals("") ){
                tf = tfPesquisa1.getText().trim();
            }
                        
            if( cbTipoDePesquisa.getSelectedItem() != null ) {
                
                if( cbTipoDePesquisa.getSelectedItem().toString().trim().equals("CATEGORIA DO PRODUTO") ){
                                
                    //MeuObjeto obj = (MeuObjeto) combobox.getSelectedItem();
                    BookInfoCategoriaDoProduto obj = (BookInfoCategoriaDoProduto) cbCategoriaDoProduto.getSelectedItem();
                    //System.out.println( "obj.ID "+obj.ID );
                    q = JPAUtil.em().createNativeQuery( "SELECT * FROM SCHEMAJMARY.PRODUTOPORFORNECEDOR WHERE ID_FORNECEDOR = ? AND ID_CATEGORIADOPRODUTO = ? AND DESCRICAOPRODUTO LIKE ?", produto_por_fornecedor.Produtoporfornecedor.class );
                    q.setParameter(1, getFornecedor().getId() );
                    q.setParameter(2, obj.ID );         
                    q.setParameter(3, "%"+tf.toUpperCase()+"%");
                    
                    if( btPrint.isEnabled() ) {
                
                        if( IDSELECIONADA > 0 ) {
                    
                            fornecedor.Fornecedor Fornecedor4 = getFornecedor();
                            if( Fornecedor4.getId() > 0 ) {
                        
                                new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
            
                                    ControleThread_Print t1 = new ControleThread_Print( getFornecedor().getId(), 2, q );         
                                    t1.setName("ControleThread_Print");           
                                    t1.start();
                                } catch( Exception e ){ JOPM JOPM = new JOPM( 2, "eventoBotaoImprimir(), \n" + e.getMessage() + "\n", this.getClass().getSimpleName() ); } } }.start(); 
                            }
                        }
                    }
                }
                else if( cbTipoDePesquisa.getSelectedItem().toString().trim().equals("CÓDIGO DO PRODUTO") ){

                    q = JPAUtil.em().createNativeQuery( "SELECT * FROM SCHEMAJMARY.PRODUTOPORFORNECEDOR WHERE ID_FORNECEDOR = ? AND CODIGOPRODUTO = ?", produto_por_fornecedor.Produtoporfornecedor.class );
                    q.setParameter(1, getFornecedor().getId() );
                    q.setParameter(2, tf.toUpperCase() );
                    
                    if( btPrint.isEnabled() ) {
                
                        if( IDSELECIONADA > 0 ) {
                    
                            fornecedor.Fornecedor Fornecedor4 = getFornecedor();
                            if( Fornecedor4.getId() > 0 ) {
                        
                                new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
            
                                    ControleThread_Print t1 = new ControleThread_Print( getFornecedor().getId(), 2, q );         
                                    t1.setName("ControleThread_Print");           
                                    t1.start();
                                } catch( Exception e ){ JOPM JOPM = new JOPM( 2, "eventoBotaoImprimir(), \n" + e.getMessage() + "\n", this.getClass().getSimpleName() ); } } }.start(); 
                            }
                        }
                    }
                }
                else if( cbTipoDePesquisa.getSelectedItem().toString().trim().equals("DESCRIÇÃO DO PRODUTO") ){
                    
                    q = JPAUtil.em().createNativeQuery( "SELECT * FROM SCHEMAJMARY.PRODUTOPORFORNECEDOR WHERE ID_FORNECEDOR = ? AND DESCRICAOPRODUTO LIKE ?", produto_por_fornecedor.Produtoporfornecedor.class );
                    q.setParameter(1, getFornecedor().getId() );
                    q.setParameter(2, "%"+tf.toUpperCase()+"%");
                    
                    if( btPrint.isEnabled() ) {
                
                        if( IDSELECIONADA > 0 ) {
                    
                            fornecedor.Fornecedor Fornecedor4 = getFornecedor();
                            if( Fornecedor4.getId() > 0 ) {
                        
                                new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
            
                                    ControleThread_Print t1 = new ControleThread_Print( getFornecedor().getId(), 2, q );         
                                    t1.setName("ControleThread_Print");           
                                    t1.start();
                                } catch( Exception e ){ JOPM JOPM = new JOPM( 2, "eventoBotaoImprimir(), \n" + e.getMessage() + "\n", this.getClass().getSimpleName() ); } } }.start(); 
                            }
                        }
                    }
                }
            }
                                                                    
        } catch( Exception e ){ /*JOPM JOPM = new JOPM( 2, "pesquisar(), \n"
                + e.getMessage() + "\n", "Menu_Pesquisa" );*/ } } }.start(); 
    }//GEN-LAST:event_btPrintActionPerformed

    private void btAtualizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAtualizarMousePressed
        pesquisar();
    }//GEN-LAST:event_btAtualizarMousePressed

    private void cbTipoDePesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoDePesquisaActionPerformed
        try{
            if( cbTipoDePesquisa.getSelectedItem() != null ) {

                if( cbTipoDePesquisa.getSelectedItem().toString().trim().equals("CATEGORIA DO PRODUTO") ){
                    lbCategoria.setVisible(true);
                    cbCategoriaDoProduto.setVisible(true);
                }
                else{
                    lbCategoria.setVisible(false);
                    cbCategoriaDoProduto.setVisible(false);
                }
            }
            pesquisar2();
        }
        catch( Exception e ){}
    }//GEN-LAST:event_cbTipoDePesquisaActionPerformed

    private void cbCategoriaDoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriaDoProdutoActionPerformed
        pesquisar2();
    }//GEN-LAST:event_cbCategoriaDoProdutoActionPerformed

    private void btSelecionarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSelecionarMousePressed
        selecionarFornecedor();
    }//GEN-LAST:event_btSelecionarMousePressed

    private void tfPesquisa1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfPesquisa1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPesquisa1MousePressed

    private void tfPesquisa1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPesquisa1KeyReleased
        pesquisar2();
    }//GEN-LAST:event_tfPesquisa1KeyReleased

    private void btSelecionar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSelecionar1MousePressed
        pesquisar2();
    }//GEN-LAST:event_btSelecionar1MousePressed

    private void btGestorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btGestorMousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 ); 
        
            if( btGestor.isEnabled() ) {
            
                if( IDSELECIONADA > 0 ) {
                    
                    fornecedor.Fornecedor Fornecedor4 = getFornecedor();
                    
                    if( Fornecedor4.getId() > 0 ) {
                        
                        Query q4 = JPAUtil.em().createNativeQuery( "SELECT * FROM SCHEMAJMARY.PRODUTOPORFORNECEDOR WHERE ID_FORNECEDOR = ?", produto_por_fornecedor.Produtoporfornecedor.class );
                        q4.setParameter(1, getFornecedor().getId() );
            
                        if(q4 != null) { 
                            
                            List<produto_por_fornecedor.Produtoporfornecedor> list4 = q4.getResultList(); 
                            
                            Produto_Por_Fornecedor_Home.Home.ControleTabs.AddTabsAoHome( "Gestor de Compras", "/fonema_e_letra_imagens/livroTp.gif", new Gestor_Home( Produto_Por_Fornecedor_Home.Home, Fornecedor4, list4 ) ); 
                        }
                    }
                    else{
                        JOPM JOptionPaneMod = new JOPM( 2, "Fornecedor Selecionado, \n"
                                + "Nenhum Fornecedor Selecionado\n" 
                                + "Para Gerar um Novo Gestor Selecione um Fornecedor" 
                                + "\n", "Fornecedor Selecionado" );
                    }
                    
                }
            }
        
        } catch( Exception e ){      } } }.start();    
        //Fonema_E_Letra_Home.Home.ControleTabs.AddTabsAoHome( "Gestor de Compras", "/fonema_e_letra_imagens/livroTp.gif", new Gestor_Home( Fonema_E_Letra_Home.Home ) );
    }//GEN-LAST:event_btGestorMousePressed

    private void pesquisar() {       
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 ); 
            
            /*String tf = "";
            if( !tfPesquisa.getText().trim().equals("") ){
                tf = tfPesquisa.getText().trim();
            }*/
            q = JPAUtil.em().createNativeQuery( "SELECT * FROM SCHEMAJMARY.PRODUTOPORFORNECEDOR WHERE ID_FORNECEDOR = ?", produto_por_fornecedor.Produtoporfornecedor.class );
            q.setParameter(1, getFornecedor().getId() );
            
            tfPesquisa.setText( getFornecedor().getNomeourazaosocial() );
            
            if(q != null) { Tabela_Pesquisa_BD_Produto_Por_Fornecedor.pesquisa(q); }
                                    
        } catch( Exception e ){ /*JOPM JOPM = new JOPM( 2, "pesquisar(), \n"
                + e.getMessage() + "\n", "Menu_Pesquisa" );*/ } } }.start(); 
    }    
    
    private void pesquisar2() {       
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 ); 
            
            String tf = "";
            if( !tfPesquisa1.getText().trim().equals("") ){
                tf = tfPesquisa1.getText().trim();
            }
                        
            if( cbTipoDePesquisa.getSelectedItem() != null ) {
                
                if( cbTipoDePesquisa.getSelectedItem().toString().trim().equals("CATEGORIA DO PRODUTO") ){
                                
                    //MeuObjeto obj = (MeuObjeto) combobox.getSelectedItem();
                    BookInfoCategoriaDoProduto obj = (BookInfoCategoriaDoProduto) cbCategoriaDoProduto.getSelectedItem();
                    //System.out.println( "obj.ID "+obj.ID );
                    q = JPAUtil.em().createNativeQuery( "SELECT * FROM SCHEMAJMARY.PRODUTOPORFORNECEDOR WHERE ID_FORNECEDOR = ? AND ID_CATEGORIADOPRODUTO = ? AND DESCRICAOPRODUTO LIKE ?", produto_por_fornecedor.Produtoporfornecedor.class );
                    q.setParameter(1, getFornecedor().getId() );
                    q.setParameter(2, obj.ID );         
                    q.setParameter(3, "%"+tf.toUpperCase()+"%");
                }
                else if( cbTipoDePesquisa.getSelectedItem().toString().trim().equals("CÓDIGO DO PRODUTO") ){

                    q = JPAUtil.em().createNativeQuery( "SELECT * FROM SCHEMAJMARY.PRODUTOPORFORNECEDOR WHERE ID_FORNECEDOR = ? AND CODIGOPRODUTO = ?", produto_por_fornecedor.Produtoporfornecedor.class );
                    q.setParameter(1, getFornecedor().getId() );
                    q.setParameter(2, tf.toUpperCase() );
                }
                else if( cbTipoDePesquisa.getSelectedItem().toString().trim().equals("DESCRIÇÃO DO PRODUTO") ){
                    
                    q = JPAUtil.em().createNativeQuery( "SELECT * FROM SCHEMAJMARY.PRODUTOPORFORNECEDOR WHERE ID_FORNECEDOR = ? AND DESCRICAOPRODUTO LIKE ?", produto_por_fornecedor.Produtoporfornecedor.class );
                    q.setParameter(1, getFornecedor().getId() );
                    q.setParameter(2, "%"+tf.toUpperCase()+"%");
                }
            }
            
            if(q != null) { Tabela_Pesquisa_BD_Produto_Por_Fornecedor.pesquisa(q); }
                                    
        } catch( Exception e ){ /*JOPM JOPM = new JOPM( 2, "pesquisar(), \n"
                + e.getMessage() + "\n", "Menu_Pesquisa" );*/ } } }.start(); 
    }
    
    private void excluir() {  
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 ); 
            
            if( btExcluir.isEnabled() ) {
            
                if( IDSELECIONADA > 0 ) {
                    
                    //////////////////////////////////////////////////////////////////////////////////////////
                    produto_por_fornecedor.Produtoporfornecedor Produtoporfornecedor = new produto_por_fornecedor.Produtoporfornecedor();
                    
                    Query q = JPAUtil.em().createNativeQuery( "SELECT * FROM SCHEMAJMARY.PRODUTOPORFORNECEDOR WHERE ID = ?", produto_por_fornecedor.Produtoporfornecedor.class );
                    q.setParameter(1, IDSELECIONADA);   
                    
                    List<produto_por_fornecedor.Produtoporfornecedor> list = q.getResultList();
                    
                    for (int i = 0; i < list.size(); i++){
                        Produtoporfornecedor = list.get(i);
                    }   
                    
                    DAOGenericoJPA DAOGenericoJPA = new DAOGenericoJPA( Produtoporfornecedor, JPAUtil.em()); 
                    DAOGenericoJPA.excluir();
                    //////////////////////////////////////////////////////////////////////////////////////////
 
                    btAlterar   .setEnabled(false);
                    btExcluir   .setEnabled(false);
                    btVisualizar.setEnabled(false);
                    pesquisar();
                }
                else{
                    JOPM JOptionPaneMod = new JOPM( 2, "ID SELECIONADA, "
                            + "\nNenhuma matéria selecionada"
                            + "\nSelecione uma matéria"
                            + "\n", "Matéria selecionada" );
                
                    tfPesquisa.requestFocus();
                }
            }
            
        } catch( Exception e ){ JOPM JOptionPaneMod = new JOPM( 2, "excluir(), \n"
                + e.getMessage() + "\n", this.getClass().getSimpleName() ); } } }.start(); 
    }
    
    private void alterarOuVisualizar(String str) {
        try {            
            if( btAlterar.isEnabled() ) {            
                if( IDSELECIONADA > 0 ) {
                    
                    produto_por_fornecedor.Produtoporfornecedor Produtoporfornecedor = new produto_por_fornecedor.Produtoporfornecedor();
                    
                    Query q = JPAUtil.em().createNativeQuery( "SELECT * FROM SCHEMAJMARY.PRODUTOPORFORNECEDOR WHERE ID = ?", produto_por_fornecedor.Produtoporfornecedor.class );
                    q.setParameter(1, IDSELECIONADA);   
                    
                    List<produto_por_fornecedor.Produtoporfornecedor> list = q.getResultList();
                    
                    for (int i = 0; i < list.size(); i++){
                        Produtoporfornecedor = list.get(i);
                    }
                    
                    if( str.equals( "Visualizar") ){
                        
                        Produto_Por_Fornecedor_New New = new Produto_Por_Fornecedor_New( Produto_Por_Fornecedor_Home, Produtoporfornecedor );
                        Produto_Por_Fornecedor_Home.Home.ControleTabs.AddTabSemControleNovo( Produto_Por_Fornecedor_Home.tabHome, "Visualizar", "/utilidades_imagens/olho.png", New );
                        New.btSalvar   .setVisible(false);
                        New.btAtualizar.setVisible(false);
                    }
                    else if( str.equals( "Alterar") ){
                        
                        Produto_Por_Fornecedor_New New = new Produto_Por_Fornecedor_New( Produto_Por_Fornecedor_Home, Produtoporfornecedor );
                        Produto_Por_Fornecedor_Home.Home.ControleTabs.AddTabSemControleNovo( Produto_Por_Fornecedor_Home.tabHome, "Alterar", "/utilidades_imagens/alterar.gif", New );
                    }
                }
                else{
                    JOPM JOptionPaneMod = new JOPM( 2, "ID SELECIONADA, "
                            + "\nNenhuma USUÁRIO selecionada"
                            + "\nSelecione uma matéria"
                            + "\n", "Matéria selecionada" );
                
                    tfPesquisa.requestFocus();
                }
            }
            
        } catch( Exception e ){ JOPM JOptionPaneMod = new JOPM( 2, "alterar(), \n"
                + e.getMessage() + "\n", this.getClass().getSimpleName() ); } //} }.start(); 
    }

    /**
     * @return the Fornecedor
     */
    public fornecedor.Fornecedor getFornecedor() {
        return Fornecedor;
    }

    /**
     * @param Fornecedor the Fornecedor to set
     */
    public void setFornecedor(fornecedor.Fornecedor Fornecedor) {
        this.Fornecedor = Fornecedor;
    }
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btAlterar;
    public javax.swing.JButton btAtualizar;
    public javax.swing.JButton btExcluir;
    public javax.swing.JButton btGestor;
    public javax.swing.JButton btPrint;
    public javax.swing.JButton btSelecionar;
    public javax.swing.JButton btSelecionar1;
    public javax.swing.JButton btVisualizar;
    public javax.swing.JComboBox cbCategoriaDoProduto;
    public javax.swing.JComboBox cbTipoDePesquisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel jpStatus1;
    private javax.swing.JLabel lbCategoria;
    public javax.swing.JTextField tfPesquisa;
    public javax.swing.JTextField tfPesquisa1;
    // End of variables declaration//GEN-END:variables
        
    Menu_Pesquisa_Produto_Por_Fornecedor Menu_Pesquisa_Produto_Por_Fornecedor;
    private void selecionarFornecedor() {
         
        Menu_Pesquisa_Produto_Por_Fornecedor = this;
        
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 ); 
            
            Fornecedor_Home Fornecedor_Home = new Fornecedor_Home( Produto_Por_Fornecedor_Home.Home, Menu_Pesquisa_Produto_Por_Fornecedor );
            JPanel jp = new JPanel();
            jp.setLayout( new BorderLayout() );
            jp.add      ( Fornecedor_Home, BorderLayout.CENTER  );
            
            Produto_Por_Fornecedor_Home.Home.ControleTabs.AddTabSemControleNovo( Produto_Por_Fornecedor_Home.tabHome, "Selecionar Fornecedor", "/utilidades_imagens/icon.png", jp ); 
            
        } catch( Exception e ){ JOPM JOptionPaneMod = new JOPM( 2, "addAbaPesquisa(), \n"
                + e.getMessage() + "\n", this.getClass().getSimpleName() ); } } }.start();    
    }
    
    private fornecedor.Fornecedor Fornecedor;
    public void setarNoJPanelFornecedorSelecionado( fornecedor.Fornecedor Fornecedor2 ) {                                                  
        try{

            setFornecedor(Fornecedor2);
            new Thread() {   @Override public void run() { try { Thread.sleep( 1 ); 
            
                pesquisar();
            
            } catch( Exception e ){ JOPM JOptionPaneMod = new JOPM( 2, "addAbaPesquisa(), \n"
                    + e.getMessage() + "\n", this.getClass().getSimpleName() ); } } }.start();  
            
        } catch( Exception e ){ JOPM JOptionPaneMod = new JOPM( 2, "setarNoJPanelFornecedorSelecionado(), \n"
                + e.getMessage() + "\n", this.getClass().getSimpleName() ); }
    }
    
    public void setarCategorias(categoria_do_produto.Categoriadoproduto Categoriadoproduto){  
        
        try{            
            Query q = JPAUtil.em().createNativeQuery( "SELECT * FROM SCHEMAJMARY.CATEGORIADOPRODUTO", categoria_do_produto.Categoriadoproduto.class );
            List<categoria_do_produto.Categoriadoproduto> list = q.getResultList();
        
            if( cbCategoriaDoProduto.getItemCount() > 0 ) { cbCategoriaDoProduto.removeAllItems(); }           
            
            int select = 0;
            for (int i = 0; i < list.size(); i++){ 
                
                if( list.get(i).getId() == Categoriadoproduto.getId() ) {
                    select = i;
                }
                                                             
                cbCategoriaDoProduto.addItem( new BookInfoCategoriaDoProduto( 
                        list.get(i).getId(), 
                        list.get(i).getNomedacategoriadoproduto()
                )
                );    
            }      
            
            cbCategoriaDoProduto.setSelectedIndex( select );
        }catch(Exception e ){} 
    }
    
}
