/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gestor;

import br.com.jmary.home.Home;
import java.util.List;
import javax.swing.JTabbedPane;

/**
 *
 * @author pc
 */
public class Gestor_Home extends javax.swing.JPanel {

    public Home                     Home;
    public JTabbedPane              tabHome;
    
    public Gestor_Home_Inicio       Inicio;
        
    /**
     * Creates new form Fonema_E_Letra_Home
     * @param Home2
     */
    public Gestor_Home( Home Home2 ) {
        initComponents();
        
        Home                       = Home2;
        tabHome                    = new JTabbedPane();
                                
        Inicio = new Gestor_Home_Inicio( this );                
    }
    
    //////////////////////////////////////////////////////////////
    public fornecedor.Fornecedor                             Fornecedor4;
    public List<produto_por_fornecedor.Produtoporfornecedor> list4;
    public Gestor_Home( Home Home2, fornecedor.Fornecedor Fornecedor44, List<produto_por_fornecedor.Produtoporfornecedor> list44 ) {
        initComponents();
        
        list4       = list44;
        Fornecedor4 = Fornecedor44;
        
        Home                       = Home2;
        tabHome                    = new JTabbedPane();
                                
        Inicio = new Gestor_Home_Inicio( this, Fornecedor44, list44 );                
    }
    //////////////////////////////////////////////////////////////

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnHome = new javax.swing.JPanel();

        javax.swing.GroupLayout pnHomeLayout = new javax.swing.GroupLayout(pnHome);
        pnHome.setLayout(pnHomeLayout);
        pnHomeLayout.setHorizontalGroup(
            pnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        pnHomeLayout.setVerticalGroup(
            pnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 209, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel pnHome;
    // End of variables declaration//GEN-END:variables
    
}
